# Generated by Django 3.1.3 on 2020-12-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Interviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('interviewee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Interviewee.interviewee')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interviewer.question')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInterviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interviewer.group')),
                ('interviewee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interviewee.interviewee')),
            ],
        ),
    ]
