# Generated by Django 3.1.3 on 2020-12-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
