# Generated by Django 3.1.3 on 2020-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewer', '0002_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response_type',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
