site_name: Activity League
theme:
  name: material
markdown_extensions:
  - admonition
  - attr_list
nav:
    - Home: 'index.md'
    - Getting Started: 'getting_started.md'
    - User Manual:
        - 'Surveyor': 'surveyor.md'
        - 'Respondent': 'respondent.md'
extra:
  generator: false
site_dir: guide