name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish Image
        uses: docker/build-push-action@v1
        with:
          tags: latest
          path: .
          dockerfile: ./Dockerfile
          repository: uclcomputerscience/comp0016_2020_21_team19/activityleague_web
          registry: docker.pkg.github.com
          username: 1kc2
          password: ${{ secrets.ACCESS_TOKEN }}
