name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ActivityLeague
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        with:
          tags: latest
          image_name: activityleague_web
          dockerfile: ActivityLeague/Dockerfile
          # repository: my-user/my-repo
          access_token: ${{ secrets.ACCESS_TOKEN }}

