name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish Image
        uses: docker/build-push-action@v1
        with:
          tags: latest
          path: .
          dockerfile: ./Dockerfile
          repository: uclcomputerscience/comp0016_2020_21_team19/activityleague_web
          registry: docker.pkg.github.com
          username: 1kc2
          password: ${{ secrets.ACCESS_TOKEN }}
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DEBUG: "False"
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

